// apps/docs/components/home/HeroSection.tsx
import Link from 'next/link'
import { cn } from '@/lib/cn'
import { ArrowRightIcon, GitHubIcon } from './icons'
import { backgrounds, buttonStyles } from './styles'
import { homeTranslations, type Locale } from './translations'

export function HeroSection({ locale }: { locale: string }) {
  const t = homeTranslations[locale as Locale]?.hero ?? homeTranslations.en.hero

  return (
    <section className="relative">
      <div className="absolute inset-0 bg-white dark:bg-neutral-950 pointer-events-none" />
      <div className={cn('absolute inset-0 pointer-events-none', backgrounds.hero)} />

      <div className="relative z-10 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12 sm:py-16 lg:py-20">
        <div className="grid lg:grid-cols-2 lg:items-stretch gap-8 lg:gap-12 mb-12 lg:mb-16">
          <div className="max-w-xl">
            <h1 className="text-4xl sm:text-5xl md:text-6xl lg:text-7xl font-bold tracking-tight mb-4 sm:mb-6 leading-[0.98]">
              <span className="text-neutral-900 dark:text-white">{t.title1}</span>
              <br />
              <span className="bg-gradient-to-r from-emerald-500 via-teal-500 to-cyan-500 bg-clip-text text-transparent">
                {t.title2}
              </span>
            </h1>
            <p className="text-base sm:text-lg text-neutral-600 dark:text-neutral-400 mb-6 sm:mb-8">
              {t.description}
            </p>
            <div className="flex flex-wrap items-center gap-3">
              <Link href={`/${locale}/docs/server`} className={cn(...buttonStyles.primary)}>
                {t.deploy}
                <ArrowRightIcon className="w-4 h-4" />
              </Link>
              <a href="mailto:info@shumoku.dev" className={cn(...buttonStyles.secondary)}>
                {t.talkToUs}
              </a>
              <a
                href="https://github.com/konoe-akitoshi/shumoku"
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center gap-1.5 text-sm text-neutral-500 dark:text-neutral-500 hover:text-neutral-800 dark:hover:text-neutral-300 transition-colors ml-1"
              >
                <GitHubIcon className="w-4 h-4" />
                {t.githubLabel}
              </a>
            </div>
          </div>

          <div className="mt-4 lg:mt-0 lg:flex-1 flex items-center">
            <div className="rounded-2xl overflow-hidden border border-neutral-200/70 dark:border-neutral-800/70 shadow-2xl">
              <img
                src="/screenshots/topology.png"
                alt="Topology viewer with live weathermap"
                className="w-full h-auto"
              />
            </div>
          </div>
        </div>

      </div>
    </section>
  )
}

// apps/website/src/lib/home/HeroSection.svelte
<script lang="ts">
  import { homeTranslations, type Locale } from '@shumoku/website-content'
  import { docsUrl } from './styles'

  let { locale }: { locale: string } = $props()
  const t = $derived(homeTranslations[locale as Locale]?.hero ?? homeTranslations.en.hero)
</script>
<section class="hero site-container">
  <div class="hero-copy">
    <h1>{t.title1}<br>{t.title2}</h1>
    <p>
      {locale === 'ja' ? 'YAMLや実際のインフラデータから、ネットワーク構成図を生成。ドキュメントへの埋め込みから、日々の運用・監視まで。' : 'Generate network diagrams from YAML and real infrastructure data. Embed them in documentation or use them for daily operations and monitoring.'}
    </p>
    <div class="hero-actions">
      <a href={docsUrl(locale, 'server')} class="site-button site-button-primary">{t.deploy}</a>
      <a href={`/${locale}/playground`} class="site-button site-button-secondary">Playground</a>
      <a
        class="text-link"
        href="https://demo.shumoku.dev/share/topologies/R71ZG1gEigiVY82YKpgDT03I"
        target="_blank"
        rel="noopener noreferrer"
        >{t.liveDemo}
        ↗</a
      >
    </div>
  </div>
  <figure>
    <img
      src="/screenshots/topology.png"
      alt="Topology viewer with live weathermap"
      width="3840"
      height="2160"
      fetchpriority="high"
    >
    <figcaption>
      {locale === 'ja' ? 'Shumoku Server — トポロジーとライブトラフィック' : 'Shumoku Server — topology and live traffic'}
    </figcaption>
  </figure>
</section>
<style>
  .hero {
    padding-block: 4.5rem 2rem;
  }
  .hero-copy {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 1.5rem 4rem;
    align-items: start;
    margin-bottom: 2.75rem;
  }
  h1 {
    grid-row: span 2;
    font-size: clamp(2.5rem, 4.7vw, 3.8rem);
    line-height: 1.17;
    letter-spacing: -0.04em;
    font-weight: 600;
  }
  p {
    max-width: 34rem;
    font-size: 1.0625rem;
    line-height: 1.85;
    color: var(--site-muted);
    padding-top: 0.25rem;
  }
  .hero-actions {
    display: flex;
    flex-wrap: wrap;
    align-items: center;
    gap: 0.75rem;
  }
  .text-link {
    font-size: 0.875rem;
    text-decoration: underline;
    text-underline-offset: 4px;
    padding: 0.5rem 0;
  }
  figure {
    margin: 0;
  }
  img {
    display: block;
    width: 100%;
    height: auto;
    border: 1px solid var(--site-line);
    border-radius: 6px;
  }
  figcaption {
    margin-top: 0.75rem;
    font-size: 0.8125rem;
    color: var(--site-muted);
  }
  @media (max-width: 750px) {
    .hero {
      padding-top: 2.75rem;
    }
    .hero-copy {
      grid-template-columns: 1fr;
      gap: 1.25rem;
      margin-bottom: 2rem;
    }
    h1 {
      grid-row: auto;
    }
  }
</style>
